// js/data.js — Datos de todos los juegos (versión ampliada)

const DATA = {

  // ===== CUAL SOBRA =====
  cualSobra: {
    facil: [
      { items: ['Perro', 'Gato', 'Conejo', 'Silla'], odd: 'Silla', reason: 'Los demás son animales' },
      { items: ['Manzana', 'Pera', 'Naranja', 'Zanahoria'], odd: 'Zanahoria', reason: 'Los demás son frutas' },
      { items: ['Rojo', 'Azul', 'Verde', 'Círculo'], odd: 'Círculo', reason: 'Los demás son colores' },
      { items: ['Cuchillo', 'Tenedor', 'Cuchara', 'Peine'], odd: 'Peine', reason: 'Los demás son cubiertos' },
      { items: ['Rosa', 'Tulipán', 'Girasol', 'Lechuga'], odd: 'Lechuga', reason: 'Los demás son flores' },
      { items: ['Zapato', 'Bota', 'Sandalia', 'Gorro'], odd: 'Gorro', reason: 'Los demás son calzado' },
      { items: ['Lunes', 'Martes', 'Jueves', 'Agosto'], odd: 'Agosto', reason: 'Los demás son días de la semana' },
      { items: ['Piano', 'Guitarra', 'Violín', 'Martillo'], odd: 'Martillo', reason: 'Los demás son instrumentos' },
      { items: ['Cama', 'Sofá', 'Silla', 'Nevera'], odd: 'Nevera', reason: 'Los demás sirven para sentarse o tumbarse' },
      { items: ['Verano', 'Invierno', 'Primavera', 'Miércoles'], odd: 'Miércoles', reason: 'Los demás son estaciones' },
      { items: ['León', 'Tigre', 'Elefante', 'Sardina'], odd: 'Sardina', reason: 'Los demás son animales terrestres' },
      { items: ['Avión', 'Barco', 'Tren', 'Sombrero'], odd: 'Sombrero', reason: 'Los demás son medios de transporte' },
      { items: ['Mesa', 'Silla', 'Armario', 'Camisa'], odd: 'Camisa', reason: 'Los demás son muebles' },
      { items: ['Naranja', 'Limón', 'Mandarina', 'Patata'], odd: 'Patata', reason: 'Los demás son cítricos' },
      { items: ['Calcetín', 'Pantalón', 'Camisa', 'Tenedor'], odd: 'Tenedor', reason: 'Los demás son ropa' },
      { items: ['Sol', 'Luna', 'Estrella', 'Piedra'], odd: 'Piedra', reason: 'Los demás están en el cielo' },
      { items: ['Médico', 'Maestro', 'Carpintero', 'Novela'], odd: 'Novela', reason: 'Los demás son profesiones' },
      { items: ['Río', 'Mar', 'Lago', 'Montaña'], odd: 'Montaña', reason: 'Los demás son masas de agua' },
      { items: ['Perro', 'Gato', 'Pájaro', 'Tractor'], odd: 'Tractor', reason: 'Los demás son animales' },
      { items: ['Ciruela', 'Uva', 'Melocotón', 'Tomate'], odd: 'Tomate', reason: 'Los demás son frutas dulces' },
    ],
    normal: [
      { items: ['Madrid', 'París', 'Berlín', 'Amazonas'], odd: 'Amazonas', reason: 'Los demás son capitales europeas' },
      { items: ['Enero', 'Febrero', 'Lunes', 'Marzo'], odd: 'Lunes', reason: 'Los demás son meses' },
      { items: ['Salmón', 'Atún', 'Merluza', 'Gallina'], odd: 'Gallina', reason: 'Los demás son peces' },
      { items: ['Fútbol', 'Tenis', 'Natación', 'Ajedrez'], odd: 'Ajedrez', reason: 'Los demás son deportes físicos' },
      { items: ['Madrid', 'Barcelona', 'Sevilla', 'Lima'], odd: 'Lima', reason: 'Los demás son ciudades españolas' },
      { items: ['Cuadro', 'Triángulo', 'Círculo', 'Ventana'], odd: 'Ventana', reason: 'Los demás son figuras geométricas' },
      { items: ['Plátano', 'Limón', 'Mango', 'Tomate'], odd: 'Tomate', reason: 'Los demás son frutas dulces' },
      { items: ['Pino', 'Roble', 'Olivo', 'Clavel'], odd: 'Clavel', reason: 'Los demás son árboles' },
      { items: ['Violín', 'Viola', 'Cello', 'Trompeta'], odd: 'Trompeta', reason: 'Los demás son instrumentos de cuerda' },
      { items: ['Venus', 'Marte', 'Júpiter', 'Luna'], odd: 'Luna', reason: 'Los demás son planetas' },
      { items: ['Grecia', 'Italia', 'España', 'Egipto'], odd: 'Egipto', reason: 'Los demás son países europeos' },
      { items: ['Café', 'Té', 'Zumo', 'Aceite'], odd: 'Aceite', reason: 'Los demás son bebidas' },
      { items: ['Abeja', 'Mariposa', 'Mosca', 'Araña'], odd: 'Araña', reason: 'Los demás son insectos' },
      { items: ['Tiburón', 'Delfín', 'Ballena', 'Águila'], odd: 'Águila', reason: 'Los demás son animales marinos' },
      { items: ['Corazón', 'Pulmón', 'Hígado', 'Rodilla'], odd: 'Rodilla', reason: 'Los demás son órganos internos' },
      { items: ['Cobre', 'Hierro', 'Oro', 'Madera'], odd: 'Madera', reason: 'Los demás son metales' },
      { items: ['Bacalao', 'Lenguado', 'Merluza', 'Pulpo'], odd: 'Pulpo', reason: 'Los demás son peces' },
      { items: ['Euros', 'Dólares', 'Libras', 'Kilómetros'], odd: 'Kilómetros', reason: 'Los demás son monedas' },
      { items: ['Lluvia', 'Nieve', 'Granizo', 'Viento'], odd: 'Viento', reason: 'Los demás son precipitaciones' },
      { items: ['Freír', 'Hervir', 'Hornear', 'Lavar'], odd: 'Lavar', reason: 'Los demás son formas de cocinar' },
      { items: ['Triángulo', 'Cuadrado', 'Pentágono', 'Esfera'], odd: 'Esfera', reason: 'Los demás son figuras planas' },
      { items: ['Telescopio', 'Microscopio', 'Periscopio', 'Estetoscopio'], odd: 'Estetoscopio', reason: 'Los demás son instrumentos ópticos' },
      { items: ['Merengue', 'Salsa', 'Flamenco', 'Cumbia'], odd: 'Flamenco', reason: 'Los demás son bailes latinoamericanos' },
      { items: ['Novela', 'Poema', 'Cuento', 'Película'], odd: 'Película', reason: 'Los demás son géneros literarios' },
      { items: ['Pintura', 'Escultura', 'Arquitectura', 'Cocina'], odd: 'Cocina', reason: 'Los demás son bellas artes' },
      { items: ['Himno', 'Bandera', 'Escudo', 'Presidente'], odd: 'Presidente', reason: 'Los demás son símbolos nacionales' },
      { items: ['Almería', 'Granada', 'Málaga', 'Valencia'], odd: 'Valencia', reason: 'Los demás son provincias andaluzas' },
      { items: ['Napoleón', 'César', 'Alejandro', 'Einstein'], odd: 'Einstein', reason: 'Los demás fueron conquistadores militares' },
      { items: ['Hebrea', 'Árabe', 'China', 'Castellana'], odd: 'Castellana', reason: 'Las otras tienen escritura no latina' },
      { items: ['Niño', 'Adolescente', 'Adulto', 'Anciano'], odd: 'Adolescente', reason: 'Los demás son etapas más definidas' },
    ],
  },

  // ===== SECUENCIAS =====
  secuencias: {
    facil: [
      { question: '1, 2, 3, 4, ?', options: ['5', '6', '7', '8'], answer: '5', hint: 'Suma 1 cada vez' },
      { question: '2, 4, 6, 8, ?', options: ['9', '10', '11', '12'], answer: '10', hint: 'Números pares' },
      { question: '5, 10, 15, 20, ?', options: ['22', '24', '25', '30'], answer: '25', hint: 'Suma 5 cada vez' },
      { question: 'Lunes, Martes, Miércoles, ?', options: ['Viernes', 'Jueves', 'Sábado', 'Domingo'], answer: 'Jueves', hint: 'Días de la semana' },
      { question: 'Enero, Febrero, Marzo, ?', options: ['Mayo', 'Junio', 'Abril', 'Julio'], answer: 'Abril', hint: 'Meses del año' },
      { question: '10, 20, 30, ?', options: ['35', '38', '40', '45'], answer: '40', hint: 'Suma 10 cada vez' },
      { question: 'Primavera, Verano, Otoño, ?', options: ['Enero', 'Lluvia', 'Invierno', 'Navidad'], answer: 'Invierno', hint: 'Las estaciones del año' },
      { question: '3, 6, 9, ?', options: ['10', '11', '12', '13'], answer: '12', hint: 'Múltiplos de 3' },
      { question: 'A, B, C, ?', options: ['F', 'E', 'D', 'G'], answer: 'D', hint: 'Letras del abecedario' },
      { question: 'Domingo, Lunes, Martes, ?', options: ['Jueves', 'Miércoles', 'Viernes', 'Sábado'], answer: 'Miércoles', hint: 'Días de la semana' },
      { question: 'Octubre, Noviembre, ?', options: ['Enero', 'Marzo', 'Diciembre', 'Septiembre'], answer: 'Diciembre', hint: 'Últimos meses del año' },
      { question: '10, 8, 6, ?', options: ['5', '4', '3', '2'], answer: '4', hint: 'Resta 2 cada vez' },
      { question: 'Uno, Dos, Tres, ?', options: ['Cinco', 'Cuatro', 'Seis', 'Siete'], answer: 'Cuatro', hint: 'Números en palabras' },
      { question: '5, 4, 3, 2, ?', options: ['0', '1', '2', '3'], answer: '1', hint: 'Cuenta atrás' },
      { question: 'A, C, E, ?', options: ['F', 'G', 'H', 'I'], answer: 'G', hint: 'Letras alternas' },
      { question: '20, 40, 60, ?', options: ['70', '75', '80', '90'], answer: '80', hint: 'Suma 20 cada vez' },
      { question: 'Lunes, Miércoles, Viernes, ?', options: ['Martes', 'Jueves', 'Domingo', 'Sábado'], answer: 'Domingo', hint: 'Días alternos' },
      { question: 'Marzo, Junio, Septiembre, ?', options: ['Octubre', 'Noviembre', 'Diciembre', 'Enero'], answer: 'Diciembre', hint: 'Cada 3 meses' },
      { question: '2, 4, 6, ?', options: ['7', '8', '9', '10'], answer: '8', hint: 'Números pares' },
      { question: '1, 2, 3, ?', options: ['4', '5', '6', '7'], answer: '4', hint: 'Suma 1 cada vez' },
    ],
    normal: [
      { question: '1, 3, 5, 7, ?', options: ['8', '9', '10', '11'], answer: '9', hint: 'Números impares' },
      { question: 'Z, Y, X, W, ?', options: ['U', 'T', 'V', 'S'], answer: 'V', hint: 'Abecedario al revés' },
      { question: '100, 90, 80, 70, ?', options: ['65', '60', '55', '50'], answer: '60', hint: 'Resta 10 cada vez' },
      { question: '2, 4, 8, 16, ?', options: ['18', '24', '32', '28'], answer: '32', hint: 'Se duplica cada vez' },
      { question: '1, 4, 9, 16, ?', options: ['20', '25', '24', '36'], answer: '25', hint: 'Son cuadrados: 1², 2², 3²...' },
      { question: '50, 45, 40, 35, ?', options: ['25', '28', '30', '32'], answer: '30', hint: 'Resta 5 cada vez' },
      { question: '7, 14, 21, 28, ?', options: ['30', '32', '35', '42'], answer: '35', hint: 'Múltiplos de 7' },
      { question: 'J, F, M, A, ?', options: ['J', 'M', 'S', 'O'], answer: 'M', hint: 'Iniciales de los meses' },
      { question: '1, 1, 2, 3, 5, ?', options: ['6', '7', '8', '9'], answer: '8', hint: 'Suma los dos anteriores (Fibonacci)' },
      { question: '64, 32, 16, 8, ?', options: ['2', '4', '6', '3'], answer: '4', hint: 'Se divide entre 2' },
      { question: '3, 5, 8, 12, ?', options: ['15', '16', '17', '18'], answer: '17', hint: 'La diferencia aumenta: +2, +3, +4, +5' },
      { question: 'DO, RE, MI, ?', options: ['SI', 'SOL', 'FA', 'LA'], answer: 'FA', hint: 'Notas musicales' },
      { question: '2, 3, 5, 7, 11, ?', options: ['12', '13', '14', '15'], answer: '13', hint: 'Son números primos' },
      { question: 'L, M, M, J, V, ?', options: ['D', 'S', 'L', 'M'], answer: 'S', hint: 'Iniciales de los días' },
      { question: '10, 11, 13, 16, 20, ?', options: ['23', '24', '25', '26'], answer: '25', hint: 'Diferencia aumenta: +1, +2, +3, +4, +5' },
      { question: '6, 12, 18, 24, ?', options: ['28', '30', '32', '36'], answer: '30', hint: 'Múltiplos de 6' },
      { question: 'I, II, III, IV, ?', options: ['V', 'VI', 'VII', 'VIII'], answer: 'V', hint: 'Números romanos' },
      { question: '81, 27, 9, 3, ?', options: ['0', '1', '2', '3'], answer: '1', hint: 'Se divide entre 3' },
      { question: '1, 8, 27, 64, ?', options: ['100', '115', '125', '130'], answer: '125', hint: 'Son cubos: 1³, 2³, 3³...' },
      { question: '0, 1, 1, 2, 3, 5, ?', options: ['6', '7', '8', '9'], answer: '8', hint: 'Fibonacci: suma los dos anteriores' },
    ],
  },

  // ===== ASOCIACIONES =====
  asociaciones: [
    { question: '¿Con qué se corta el pan?', options: ['Cuchara', 'Cuchillo', 'Tenedor', 'Pincel'], answer: 'Cuchillo' },
    { question: '¿Dónde viven los peces?', options: ['En el árbol', 'En el desierto', 'En el agua', 'En la nieve'], answer: 'En el agua' },
    { question: '¿Qué se usa para escribir?', options: ['Tijeras', 'Bolígrafo', 'Peine', 'Llave'], answer: 'Bolígrafo' },
    { question: '¿Con qué se barre el suelo?', options: ['Escoba', 'Tenedor', 'Paraguas', 'Silla'], answer: 'Escoba' },
    { question: '¿Qué usas para ver de noche?', options: ['Paraguas', 'Linterna', 'Sombrero', 'Guante'], answer: 'Linterna' },
    { question: '¿Dónde se compra el pan?', options: ['En la farmacia', 'En la panadería', 'En el banco', 'En la biblioteca'], answer: 'En la panadería' },
    { question: '¿Qué se usa para peinar el pelo?', options: ['Cepillo', 'Cuchillo', 'Llave', 'Esponja'], answer: 'Cepillo' },
    { question: '¿Con qué se come la sopa?', options: ['Tenedor', 'Cuchillo', 'Cuchara', 'Vaso'], answer: 'Cuchara' },
    { question: '¿Dónde guardas la ropa?', options: ['En la nevera', 'En el armario', 'En el jardín', 'En la cocina'], answer: 'En el armario' },
    { question: '¿Con qué se abre una cerradura?', options: ['Cuchillo', 'Llave', 'Tenedor', 'Tijeras'], answer: 'Llave' },
    { question: '¿Qué animal da la leche?', options: ['Perro', 'Gato', 'Vaca', 'Gallina'], answer: 'Vaca' },
    { question: '¿Qué animal pone huevos?', options: ['Vaca', 'Oveja', 'Gallina', 'Caballo'], answer: 'Gallina' },
    { question: '¿Dónde se guardan los medicamentos?', options: ['En la cocina', 'En el botiquín', 'En el garaje', 'En el jardín'], answer: 'En el botiquín' },
    { question: '¿Con qué se friega la vajilla?', options: ['Pluma', 'Estropajo', 'Peine', 'Cepillo de dientes'], answer: 'Estropajo' },
    { question: '¿Dónde se conserva la comida fría?', options: ['En el armario', 'En la nevera', 'En el horno', 'En la mesa'], answer: 'En la nevera' },
    { question: '¿Con qué te tapas cuando llueve?', options: ['Gorra', 'Abrigo', 'Paraguas', 'Bufanda'], answer: 'Paraguas' },
    { question: '¿Con qué se enciende una vela?', options: ['Agua', 'Cerillas', 'Sal', 'Papel'], answer: 'Cerillas' },
    { question: '¿Qué se usa para clavar un clavo?', options: ['Destornillador', 'Llave inglesa', 'Martillo', 'Pinzas'], answer: 'Martillo' },
    { question: '¿Con qué se corta el papel?', options: ['Pegamento', 'Tijeras', 'Regla', 'Goma'], answer: 'Tijeras' },
    { question: '¿Qué se usa para ver mejor de lejos?', options: ['Linterna', 'Gafas', 'Espejo', 'Lupa'], answer: 'Gafas' },
    { question: '¿Dónde se duerme?', options: ['En la silla', 'En el suelo', 'En la cama', 'En la mesa'], answer: 'En la cama' },
    { question: '¿Qué se usa para secar la ropa?', options: ['Plancha', 'Tendedero', 'Nevera', 'Escoba'], answer: 'Tendedero' },
    { question: '¿Con qué se pega papel?', options: ['Tijeras', 'Pegamento', 'Lápiz', 'Regla'], answer: 'Pegamento' },
    { question: '¿Qué mide la temperatura?', options: ['Báscula', 'Reloj', 'Termómetro', 'Regla'], answer: 'Termómetro' },
    { question: '¿Con qué se limpian los dientes?', options: ['Peine', 'Esponja', 'Cepillo de dientes', 'Toalla'], answer: 'Cepillo de dientes' },
    { question: '¿Dónde se cocinan los alimentos?', options: ['En el baño', 'En el dormitorio', 'En la cocina', 'En el garaje'], answer: 'En la cocina' },
    { question: '¿Con qué se plancha la ropa?', options: ['Secador', 'Plancha', 'Escoba', 'Aspiradora'], answer: 'Plancha' },
    { question: '¿Dónde se lava la ropa?', options: ['En la nevera', 'En la lavadora', 'En el horno', 'En el armario'], answer: 'En la lavadora' },
    { question: '¿Qué se usa para saber la hora?', options: ['Termómetro', 'Báscula', 'Reloj', 'Brújula'], answer: 'Reloj' },
    { question: '¿Con qué se limpia el suelo húmedo?', options: ['Escoba', 'Fregona', 'Aspiradora', 'Plumero'], answer: 'Fregona' },
    { question: '¿Dónde se pone el pan para tostarlo?', options: ['En la nevera', 'En la tostadora', 'En el lavabo', 'En la mesa'], answer: 'En la tostadora' },
    { question: '¿Qué se usa para pesarse?', options: ['Termómetro', 'Reloj', 'Báscula', 'Regla'], answer: 'Báscula' },
    { question: '¿Con qué se seca el pelo?', options: ['Plancha', 'Secador', 'Toalla eléctrica', 'Ventilador'], answer: 'Secador' },
    { question: '¿Qué se usa para ver objetos pequeños?', options: ['Telescopio', 'Lupa', 'Prismáticos', 'Espejo'], answer: 'Lupa' },
    { question: '¿Dónde se tira la basura?', options: ['En el suelo', 'En la papelera', 'En la nevera', 'En el sofá'], answer: 'En la papelera' },
    { question: '¿Con qué se toman las pastillas?', options: ['Comida', 'Agua', 'Zumo de naranja', 'Leche'], answer: 'Agua' },
    { question: '¿Qué hace el médico con el estetoscopio?', options: ['Mide la tensión', 'Escucha el corazón', 'Saca sangre', 'Pone una venda'], answer: 'Escucha el corazón' },
    { question: '¿Con qué se ata el calzado?', options: ['Botones', 'Cremallera', 'Cordones', 'Velcro'], answer: 'Cordones' },
    { question: '¿Dónde se pone el dinero?', options: ['En el bolsillo o cartera', 'En la mochila', 'En el libro', 'En la mesa'], answer: 'En el bolsillo o cartera' },
    { question: '¿Con qué se protegen los ojos del sol?', options: ['Gorra', 'Gafas de sol', 'Crema solar', 'Paraguas'], answer: 'Gafas de sol' },
    { question: '¿Dónde se guardan los libros?', options: ['En la nevera', 'En la estantería', 'En el armario', 'En el cajón'], answer: 'En la estantería' },
    { question: '¿Qué se usa para aspirar el polvo?', options: ['Fregona', 'Escoba', 'Aspiradora', 'Plumero'], answer: 'Aspiradora' },
    { question: '¿Con qué se orienta uno sin móvil?', options: ['Reloj', 'Mapa', 'Libro', 'Linterna'], answer: 'Mapa' },
    { question: '¿Qué se usa para quitar el polvo de los muebles?', options: ['Fregona', 'Plumero', 'Esponja', 'Estropajo'], answer: 'Plumero' },
    { question: '¿Dónde se guardan los zapatos?', options: ['En el zapatero', 'En la nevera', 'En el armario de ropa', 'En la cocina'], answer: 'En el zapatero' },
    { question: '¿Con qué se sujeta el pelo?', options: ['Peine', 'Horquilla', 'Goma', 'Horquilla o goma'], answer: 'Horquilla o goma' },
    { question: '¿Qué se usa para llamar a alguien?', options: ['Carta', 'Teléfono', 'Libro', 'Espejo'], answer: 'Teléfono' },
    { question: '¿Con qué se ve la televisión a distancia?', options: ['Radio', 'Mando a distancia', 'Teléfono', 'Libro'], answer: 'Mando a distancia' },
    { question: '¿Dónde se compran los medicamentos?', options: ['En el mercado', 'En la farmacia', 'En el banco', 'En el supermercado'], answer: 'En la farmacia' },
    { question: '¿Qué se usa para no olvidar las citas?', options: ['Espejo', 'Agenda', 'Radio', 'Escoba'], answer: 'Agenda' },
  ],

  // ===== ORDEN LOGICO =====
  ordenLogico: [
    { question: 'Ordena los pasos para hacer café:', steps: ['Hervir el agua', 'Poner el café en la taza', 'Beber el café'], correct: [0, 1, 2] },
    { question: 'Ordena los pasos para lavarte los dientes:', steps: ['Enjuagarte la boca', 'Poner pasta en el cepillo', 'Cepillarte los dientes'], correct: [1, 2, 0] },
    { question: 'Ordena los pasos para una llamada:', steps: ['Colgar el teléfono', 'Marcar el número', 'Coger el teléfono'], correct: [2, 1, 0] },
    { question: 'Ordena los pasos para vestirte:', steps: ['Ponerte los zapatos', 'Levantarte de la cama', 'Ponerte la ropa'], correct: [1, 2, 0] },
    { question: 'Ordena la rutina del desayuno:', steps: ['Fregar la taza', 'Preparar el desayuno', 'Desayunar'], correct: [1, 2, 0] },
    { question: 'Ordena los pasos para comprar en la tienda:', steps: ['Pagar en la caja', 'Coger la cesta', 'Elegir los productos'], correct: [1, 2, 0] },
    { question: 'Ordena los pasos para plantar una flor:', steps: ['Regar la planta', 'Hacer un hoyo', 'Poner la semilla'], correct: [1, 2, 0] },
    { question: 'Ordena los pasos para leer un libro:', steps: ['Cerrar el libro', 'Abrir el libro', 'Leer las páginas'], correct: [1, 2, 0] },
    { question: 'Ordena de menor a mayor:', steps: ['Cien', 'Diez', 'Mil'], correct: [1, 0, 2] },
    { question: 'Ordena los pasos para freír un huevo:', steps: ['Poner el huevo en la sartén', 'Calentar el aceite', 'Apagar el fuego y servir'], correct: [1, 0, 2] },
    { question: 'Ordena los pasos para ducharte:', steps: ['Secarte con la toalla', 'Abrir el grifo', 'Jabonarte'], correct: [1, 2, 0] },
    { question: 'Ordena los pasos para enviar una carta:', steps: ['Echarla al buzón', 'Escribir la carta', 'Meter la carta en el sobre'], correct: [1, 2, 0] },
    { question: 'Ordena estas estaciones de mayor a menor calor:', steps: ['Primavera', 'Verano', 'Invierno'], correct: [1, 0, 2] },
    { question: 'Ordena del día más temprano al más tarde:', steps: ['Mediodía', 'Amanecer', 'Medianoche'], correct: [1, 0, 2] },
    { question: 'Ordena los pasos para hacer la cama:', steps: ['Poner la almohada', 'Extender las sábanas', 'Levantarse'], correct: [2, 1, 0] },
    { question: 'Ordena los pasos para hacer un bocadillo:', steps: ['Comer el bocadillo', 'Cortar el pan', 'Poner el relleno'], correct: [1, 2, 0] },
    { question: 'Ordena los pasos para regar las plantas:', steps: ['Llenar el regador', 'Echar el agua a la planta', 'Vaciar el regador sobrante'], correct: [0, 1, 2] },
    { question: 'Ordena estos momentos del día:', steps: ['Tarde', 'Mañana', 'Noche'], correct: [1, 0, 2] },
    { question: 'Ordena los pasos para hacer una tortilla:', steps: ['Batir los huevos', 'Verter en la sartén', 'Dar la vuelta'], correct: [0, 1, 2] },
    { question: 'Ordena de menor a mayor:', steps: ['Quince', 'Cinco', 'Cincuenta'], correct: [1, 0, 2] },
    { question: 'Ordena los pasos para preparar un té:', steps: ['Sacar la bolsita', 'Hervir el agua', 'Dejar reposar'], correct: [1, 2, 0] },
    { question: 'Ordena los pasos para ir al médico:', steps: ['Salir de la consulta', 'Pedir cita', 'Entrar a la consulta'], correct: [1, 2, 0] },
    { question: 'Ordena los pasos para lavar los platos:', steps: ['Aclarar con agua', 'Frotar con el estropajo', 'Echar el jabón'], correct: [2, 1, 0] },
    { question: 'Ordena del más pequeño al más grande:', steps: ['Ciudad', 'Barrio', 'País'], correct: [1, 0, 2] },
    { question: 'Ordena los pasos para salir de casa:', steps: ['Cerrar la puerta con llave', 'Ponerte el abrigo', 'Coger las llaves'], correct: [1, 2, 0] },
    { question: 'Ordena los pasos para ver una película:', steps: ['Apagar la tele', 'Elegir la película', 'Ver la película'], correct: [1, 2, 0] },
    { question: 'Ordena los pasos para hacer la compra online:', steps: ['Pagar', 'Buscar el producto', 'Añadir al carrito'], correct: [1, 2, 0] },
    { question: 'Ordena las etapas de la vida:', steps: ['Vejez', 'Niñez', 'Adultez'], correct: [1, 2, 0] },
    { question: 'Ordena los pasos para hacer una foto:', steps: ['Ver la foto tomada', 'Encuadrar el momento', 'Pulsar el botón'], correct: [1, 2, 0] },
    { question: 'Ordena los pasos para ir al mercado:', steps: ['Pagar al vendedor', 'Elegir la fruta', 'Llegar al mercado'], correct: [2, 1, 0] },
  ],

  // ===== ATENCION VISUAL =====
  atencionVisual: [
    { question: '¿Cuál es diferente?', items: ['🌸', '🌸', '🌸', '🌹', '🌸', '🌸', '🌸', '🌸', '🌸'], odd: 3, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🟡', '🟡', '🟡', '🟡', '🔴', '🟡', '🟡', '🟡', '🟡'], odd: 4, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🐶', '🐶', '🐱', '🐶', '🐶', '🐶', '🐶', '🐶', '🐶'], odd: 2, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['⭐', '⭐', '⭐', '⭐', '⭐', '⭐', '⭐', '🌙', '⭐'], odd: 7, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🍎', '🍎', '🍎', '🍊', '🍎', '🍎', '🍎', '🍎', '🍎'], odd: 3, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🏠', '🏠', '🏠', '🏠', '🏡', '🏠', '🏠', '🏠', '🏠', '🏠', '🏠', '🏠'], odd: 4, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🌞', '🌞', '🌞', '🌞', '🌞', '🌝', '🌞', '🌞', '🌞', '🌞', '🌞', '🌞'], odd: 5, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🎵', '🎵', '🎵', '🎵', '🎵', '🎵', '🎵', '🎶', '🎵', '🎵', '🎵', '🎵'], odd: 7, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🌴', '🌴', '🌳', '🌴', '🌴', '🌴', '🌴', '🌴', '🌴'], odd: 2, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🚗', '🚗', '🚗', '🚗', '🚗', '🚗', '🚙', '🚗', '🚗'], odd: 6, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['💙', '💙', '💙', '💙', '💙', '💙', '💙', '💙', '❤️', '💙', '💙', '💙'], odd: 8, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🍕', '🍕', '🍕', '🍕', '🍕', '🌮', '🍕', '🍕', '🍕'], odd: 5, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🐝', '🐝', '🐝', '🦋', '🐝', '🐝', '🐝', '🐝', '🐝'], odd: 3, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🎈', '🎈', '🎈', '🎈', '🎈', '🎈', '🎀', '🎈', '🎈', '🎈', '🎈', '🎈'], odd: 6, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🍋', '🍋', '🍋', '🍋', '🍋', '🍋', '🍋', '🍋', '🍊', '🍋', '🍋', '🍋'], odd: 8, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🐠', '🐠', '🐠', '🐟', '🐠', '🐠', '🐠', '🐠', '🐠'], odd: 3, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🌷', '🌷', '🌷', '🌷', '🌷', '🌷', '🌸', '🌷', '🌷', '🌷', '🌷', '🌷'], odd: 6, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🐘', '🐘', '🐘', '🐘', '🦏', '🐘', '🐘', '🐘', '🐘'], odd: 4, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['☁️', '☁️', '☁️', '☁️', '☁️', '☁️', '☁️', '⛅', '☁️', '☁️', '☁️', '☁️'], odd: 7, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🍇', '🍇', '🍇', '🍇', '🍇', '🍓', '🍇', '🍇', '🍇'], odd: 5, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🔵', '🔵', '🔵', '🟢', '🔵', '🔵', '🔵', '🔵', '🔵', '🔵', '🔵', '🔵'], odd: 3, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🐓', '🐓', '🐓', '🐓', '🐓', '🦆', '🐓', '🐓', '🐓'], odd: 5, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🍦', '🍦', '🍦', '🍦', '🍦', '🍦', '🍦', '🍧', '🍦', '🍦', '🍦', '🍦'], odd: 7, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🌵', '🌵', '🌵', '🌴', '🌵', '🌵', '🌵', '🌵', '🌵'], odd: 3, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['⚽', '⚽', '⚽', '⚽', '⚽', '⚽', '🏀', '⚽', '⚽', '⚽', '⚽', '⚽'], odd: 6, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🦁', '🦁', '🦁', '🐯', '🦁', '🦁', '🦁', '🦁', '🦁'], odd: 3, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🍄', '🍄', '🍄', '🍄', '🍄', '🌿', '🍄', '🍄', '🍄'], odd: 5, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🎸', '🎸', '🎸', '🎸', '🎸', '🎸', '🎸', '🎺', '🎸', '🎸', '🎸', '🎸'], odd: 7, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🏖️', '🏖️', '🏖️', '🏔️', '🏖️', '🏖️', '🏖️', '🏖️', '🏖️'], odd: 3, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🦜', '🦜', '🦜', '🦜', '🦜', '🦜', '🐦', '🦜', '🦜', '🦜', '🦜', '🦜'], odd: 6, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🍰', '🍰', '🍰', '🍰', '🎂', '🍰', '🍰', '🍰', '🍰'], odd: 4, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🌊', '🌊', '🌊', '🌊', '🌊', '🌊', '🌊', '🌋', '🌊', '🌊', '🌊', '🌊'], odd: 7, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🐌', '🐌', '🐌', '🐛', '🐌', '🐌', '🐌', '🐌', '🐌'], odd: 3, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🎃', '🎃', '🎃', '🎃', '🎃', '🎄', '🎃', '🎃', '🎃', '🎃', '🎃', '🎃'], odd: 5, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🍩', '🍩', '🍩', '🍩', '🍪', '🍩', '🍩', '🍩', '🍩'], odd: 4, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🐬', '🐬', '🐬', '🐳', '🐬', '🐬', '🐬', '🐬', '🐬'], odd: 3, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🌺', '🌺', '🌺', '🌺', '🌺', '🌺', '🌻', '🌺', '🌺', '🌺', '🌺', '🌺'], odd: 6, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🏡', '🏡', '🏡', '🏡', '🏡', '🏰', '🏡', '🏡', '🏡'], odd: 5, cols: 3 },
    { question: '¿Cuál es diferente?', items: ['🐰', '🐰', '🐰', '🐰', '🐰', '🐰', '🐰', '🐹', '🐰', '🐰', '🐰', '🐰'], odd: 7, cols: 4 },
    { question: '¿Cuál es diferente?', items: ['🍜', '🍜', '🍜', '🍝', '🍜', '🍜', '🍜', '🍜', '🍜'], odd: 3, cols: 3 },
  ],

  // ===== PALABRAS DESORDENADAS =====
  // REGLA: 'scrambled' es siempre DIFERENTE a 'answer'. Las opciones son palabras reales en español.
  palabras: [
    // FÁCIL (4 letras, palabras cotidianas)
    { scrambled: 'SAEM', options: ['MESA', 'MISA', 'MASA', 'MUSA'], answer: 'MESA' },
    { scrambled: 'OTAG', options: ['GATO', 'PATO', 'RATO', 'DATO'], answer: 'GATO' },
    { scrambled: 'NALU', options: ['LUNA', 'LONA', 'LANA', 'LENA'], answer: 'LUNA' },
    { scrambled: 'LAAS', options: ['SALA', 'BALA', 'MALA', 'TALA'], answer: 'SALA' },
    { scrambled: 'RAMO', options: ['AMOR', 'ROMA', 'MORA', 'LOMA'], answer: 'AMOR' },
    { scrambled: 'EPRO', options: ['PERO', 'PURO', 'PARA', 'PERA'], answer: 'PERO' },
    { scrambled: 'AIRT', options: ['TIRA', 'FIRA', 'MIRA', 'GIRA'], answer: 'TIRA' },
    { scrambled: 'ELAV', options: ['VALE', 'BALE', 'SALE', 'MALE'], answer: 'VALE' },
    { scrambled: 'ARBO', options: ['OBRA', 'HORA', 'BOCA', 'ROCA'], answer: 'OBRA' },
    { scrambled: 'ODAN', options: ['NADO', 'LADO', 'DADO', 'FADO'], answer: 'NADO' },
    { scrambled: 'EADS', options: ['SEDA', 'PEDA', 'SODA', 'SANA'], answer: 'SEDA' },
    { scrambled: 'ANIP', options: ['PINA', 'BINA', 'MINA', 'FINA'], answer: 'PINA' },
    { scrambled: 'TARO', options: ['ROTA', 'BOTA', 'NOTA', 'SOTA'], answer: 'ROTA' },
    { scrambled: 'MAOC', options: ['COMA', 'ROMA', 'LOMA', 'GOMA'], answer: 'COMA' },
    { scrambled: 'ANEV', options: ['VENA', 'PENA', 'CENA', 'RENA'], answer: 'VENA' },
    { scrambled: 'ALCO', options: ['COLA', 'SOLA', 'BOLA', 'MOLA'], answer: 'COLA' },
    { scrambled: 'EPAN', options: ['PENA', 'BENA', 'LENA', 'RENA'], answer: 'PENA' },
    { scrambled: 'OSPU', options: ['PUSO', 'MUSO', 'RUSO', 'FUSO'], answer: 'PUSO' },
    { scrambled: 'AJTE', options: ['TEJA', 'DEJA', 'REJA', 'SEJA'], answer: 'TEJA' },
    { scrambled: 'UBNE', options: ['NUBE', 'TUBO', 'CUBO', 'RUBE'], answer: 'NUBE' },
    // NORMAL (5-6 letras, palabras conocidas)
    { scrambled: 'SACME', options: ['CAMSE', 'MESAS', 'CAMPO', 'CAMAS'], answer: 'CAMAS' },
    { scrambled: 'LACSE', options: ['CLASE', 'CLARO', 'CLAVE', 'CLAME'], answer: 'CLASE' },
    { scrambled: 'DAPRE', options: ['PARED', 'PAREO', 'PADRE', 'PALEO'], answer: 'PARED' },
    { scrambled: 'BOLAT', options: ['TABLA', 'HABLA', 'SABLA', 'CABLA'], answer: 'TABLA' },
    { scrambled: 'RACOP', options: ['CAMPO', 'CAMPO', 'PARCA', 'CAPRO'], answer: 'CAMPO' },
    { scrambled: 'LOSCA', options: ['COLSA', 'OSCAR', 'COLAS', 'COLAS'], answer: 'COLAS' },
    { scrambled: 'TANOP', options: ['PIANO', 'PLANO', 'PANTO', 'PAÑO'], answer: 'PIANO' },
    { scrambled: 'REDMA', options: ['MADRE', 'PADRE', 'LADRE', 'CADRE'], answer: 'MADRE' },
    { scrambled: 'LEPAS', options: ['PLASE', 'PALES', 'SALES', 'MALES'], answer: 'SALES' },
    { scrambled: 'OBSAL', options: ['BOLAS', 'SOLAS', 'VOLAS', 'MOLAS'], answer: 'BOLAS' },
    { scrambled: 'OCARB', options: ['BARCO', 'PARCO', 'MARCO', 'NARCO'], answer: 'BARCO' },
    { scrambled: 'ACAMS', options: ['CASMA', 'MASCA', 'CAMSA', 'MACAS'], answer: 'MASCA' },
    { scrambled: 'BLANOC', options: ['BLANCO', 'FRANCO', 'BRANCO', 'PLANCO'], answer: 'BLANCO' },
    { scrambled: 'NARAJA', options: ['NARANJA', 'MORANJA', 'RARANJA', 'LARANJA'], answer: 'NARANJA' },
    { scrambled: 'TRAJES', options: ['TARJES', 'CAJETS', 'TRAJES', 'JARTES'], answer: 'TRAJES' },
    { scrambled: 'SPEJOS', options: ['ESPEJOS', 'POSEJOS', 'ESPETOS', 'ESTEJOS'], answer: 'ESPEJOS' },
    { scrambled: 'TANVEA', options: ['VENTANA', 'GAVENTA', 'VANETA', 'HAVENTA'], answer: 'VENTANA' },
    { scrambled: 'APSCAL', options: ['LAPAS', 'CAPAS', 'PALACS', 'PLACAS'], answer: 'PLACAS' },
    { scrambled: 'ELOFR', options: ['FLORE', 'FOLER', 'LOFER', 'FREOL'], answer: 'FLORE' },
    { scrambled: 'ATREC', options: ['CARTA', 'TRACE', 'CARET', 'TORCA'], answer: 'CARTA' },
  ],

  // ===== CATEGORIAS =====
  categorias: [
    { question: '¿Cuál es una fruta?', options: ['Zanahoria', 'Lechuga', 'Sandía', 'Tomate'], answer: 'Sandía' },
    { question: '¿Cuál pertenece al baño?', options: ['Sartén', 'Jabón', 'Almohada', 'Tenedor'], answer: 'Jabón' },
    { question: '¿Cuál es un animal de granja?', options: ['Tigre', 'Delfín', 'Vaca', 'Pingüino'], answer: 'Vaca' },
    { question: '¿Cuál es un mueble?', options: ['Camisa', 'Armario', 'Cerezas', 'Zapato'], answer: 'Armario' },
    { question: '¿Cuál es un color?', options: ['Redondo', 'Duro', 'Azul', 'Alto'], answer: 'Azul' },
    { question: '¿Cuál es un instrumento musical?', options: ['Cinturón', 'Guitarra', 'Silla', 'Ventana'], answer: 'Guitarra' },
    { question: '¿Cuál es un medio de transporte?', options: ['Montaña', 'Libro', 'Autobús', 'Flor'], answer: 'Autobús' },
    { question: '¿Cuál es una profesión?', options: ['Pájaro', 'Mesa', 'Médico', 'Luna'], answer: 'Médico' },
    { question: '¿Cuál es un planeta?', options: ['Madrid', 'Marte', 'Nilo', 'Pirámide'], answer: 'Marte' },
    { question: '¿Cuál es una herramienta?', options: ['Gato', 'Nube', 'Martillo', 'Libro'], answer: 'Martillo' },
    { question: '¿Cuál es un deporte?', options: ['Pizza', 'Fútbol', 'Cuchara', 'Ventana'], answer: 'Fútbol' },
    { question: '¿Cuál es una flor?', options: ['Limón', 'Silla', 'Rosa', 'Perro'], answer: 'Rosa' },
    { question: '¿Cuál es un país?', options: ['Otoño', 'Azul', 'Francia', 'Cama'], answer: 'Francia' },
    { question: '¿Cuál va en la cocina?', options: ['Almohada', 'Sartén', 'Televisor', 'Espejo'], answer: 'Sartén' },
    { question: '¿Cuál es un insecto?', options: ['Trucha', 'Mariposa', 'Ardilla', 'Ballena'], answer: 'Mariposa' },
    { question: '¿Cuál es una estación del año?', options: ['Lunes', 'Norte', 'Verano', 'Noche'], answer: 'Verano' },
    { question: '¿Cuál es una verdura?', options: ['Pera', 'Uva', 'Brócoli', 'Melón'], answer: 'Brócoli' },
    { question: '¿Cuál es un número?', options: ['Azul', 'Redondo', 'Grande', 'Doce'], answer: 'Doce' },
    { question: '¿Cuál se usa para escribir?', options: ['Espejo', 'Silla', 'Bolígrafo', 'Tenedor'], answer: 'Bolígrafo' },
    { question: '¿Cuál es un pez?', options: ['Paloma', 'Ratón', 'Sardina', 'Toro'], answer: 'Sardina' },
    { question: '¿Cuál es una ciudad española?', options: ['Roma', 'Lisboa', 'Sevilla', 'París'], answer: 'Sevilla' },
    { question: '¿Cuál es un mamífero?', options: ['Serpiente', 'Águila', 'Ballena', 'Rana'], answer: 'Ballena' },
    { question: '¿Cuál es un metal?', options: ['Madera', 'Oro', 'Plástico', 'Algodón'], answer: 'Oro' },
    { question: '¿Cuál es una bebida?', options: ['Pan', 'Aceite', 'Leche', 'Arroz'], answer: 'Leche' },
    { question: '¿Cuál es un árbol?', options: ['Rosa', 'Clavel', 'Roble', 'Tulipán'], answer: 'Roble' },
    { question: '¿Cuál pertenece al dormitorio?', options: ['Nevera', 'Horno', 'Almohada', 'Lavadora'], answer: 'Almohada' },
    { question: '¿Cuál es un continente?', options: ['Amazonas', 'Europa', 'Mediterráneo', 'Pacífico'], answer: 'Europa' },
    { question: '¿Cuál es un día laborable?', options: ['Sábado', 'Domingo', 'Lunes', 'Festivo'], answer: 'Lunes' },
    { question: '¿Cuál es un animal marino?', options: ['Camello', 'Lobo', 'Pulpo', 'Buitre'], answer: 'Pulpo' },
    { question: '¿Cuál es un condimento?', options: ['Pan', 'Sal', 'Leche', 'Arroz'], answer: 'Sal' },
    { question: '¿Cuál es un color frío?', options: ['Rojo', 'Naranja', 'Azul', 'Amarillo'], answer: 'Azul' },
    { question: '¿Cuál es un animal nocturno?', options: ['Gallina', 'Paloma', 'Murciélago', 'Gorrión'], answer: 'Murciélago' },
    { question: '¿Cuál es un mes de verano?', options: ['Febrero', 'Noviembre', 'Agosto', 'Marzo'], answer: 'Agosto' },
    { question: '¿Cuál es un idioma?', options: ['Italia', 'Francés', 'España', 'Europa'], answer: 'Francés' },
    { question: '¿Cuál es un órgano del cuerpo?', options: ['Rodilla', 'Corazón', 'Músculo', 'Hueso'], answer: 'Corazón' },
    { question: '¿Cuál es un vegetal de hoja verde?', options: ['Zanahoria', 'Remolacha', 'Espinaca', 'Cebolla'], answer: 'Espinaca' },
    { question: '¿Cuál es un tipo de pasta?', options: ['Arroz', 'Lentejas', 'Espaguetis', 'Garbanzos'], answer: 'Espaguetis' },
    { question: '¿Cuál es un animal doméstico?', options: ['Cocodrilo', 'Jirafa', 'Perro', 'Gorila'], answer: 'Perro' },
    { question: '¿Cuál es una prenda de abrigo?', options: ['Camiseta', 'Bañador', 'Bufanda', 'Chanclas'], answer: 'Bufanda' },
    { question: '¿Cuál es un mineral?', options: ['Trigo', 'Diamante', 'Madera', 'Lana'], answer: 'Diamante' },
    { question: '¿Cuál es un deporte acuático?', options: ['Tenis', 'Golf', 'Natación', 'Ciclismo'], answer: 'Natación' },
    { question: '¿Cuál es una legumbre?', options: ['Patata', 'Zanahoria', 'Lenteja', 'Pimiento'], answer: 'Lenteja' },
    { question: '¿Cuál es un electrodoméstico?', options: ['Espejo', 'Silla', 'Lavadora', 'Mesa'], answer: 'Lavadora' },
    { question: '¿Cuál es un tipo de baile?', options: ['Guitarra', 'Tambor', 'Flamenco', 'Flauta'], answer: 'Flamenco' },
    { question: '¿Cuál es una moneda?', options: ['Billete', 'Euro', 'Cheque', 'Tarjeta'], answer: 'Euro' },
    { question: '¿Cuál es un ave?', options: ['Rana', 'Salamandra', 'Cigüeña', 'Tritón'], answer: 'Cigüeña' },
    { question: '¿Cuál es una herramienta de jardín?', options: ['Sartén', 'Rastrillo', 'Plancha', 'Cuchara'], answer: 'Rastrillo' },
    { question: '¿Cuál es un tipo de sombrero?', options: ['Guante', 'Bufanda', 'Boina', 'Cinturón'], answer: 'Boina' },
    { question: '¿Cuál es un tipo de pan?', options: ['Galleta', 'Croissant', 'Baguette', 'Bizcocho'], answer: 'Baguette' },
    { question: '¿Cuál es un reptil?', options: ['Delfín', 'Ballena', 'Cocodrilo', 'Tiburón'], answer: 'Cocodrilo' },
  ],

  // ===== MEMORIA BREVE =====
  memoriaBreve: [
    { showItems: ['🍎', '🌟', '🎵'], question: '¿Cuál de estos NO estaba?', options: ['🍎', '🌟', '🎵', '🎸'], answer: '🎸' },
    { showItems: ['🐶', '🌈', '⚽'], question: '¿Cuál de estos estaba?', options: ['🐱', '🌈', '🎾', '🏀'], answer: '🌈' },
    { showItems: ['🏠', '🚗', '🌺'], question: '¿Cuál de estos NO estaba?', options: ['🏠', '🚗', '🌺', '🌻'], answer: '🌻' },
    { showItems: ['🍕', '🎂', '☕'], question: '¿Cuál de estos estaba?', options: ['🍔', '🎂', '🍜', '🍰'], answer: '🎂' },
    { showItems: ['🌙', '⭐', '☀️'], question: '¿Cuál de estos NO estaba?', options: ['🌙', '⭐', '☀️', '🌤️'], answer: '🌤️' },
    { showItems: ['🐘', '🦁', '🦒'], question: '¿Cuál de estos estaba?', options: ['🐧', '🐬', '🦁', '🐊'], answer: '🦁' },
    { showItems: ['🎩', '👓', '🧤'], question: '¿Cuál de estos NO estaba?', options: ['🎩', '👓', '🧤', '👒'], answer: '👒' },
    { showItems: ['🌹', '🌷', '🌻'], question: '¿Cuál de estos estaba?', options: ['🌸', '🌹', '🍀', '🌿'], answer: '🌹' },
    { showItems: ['📚', '✏️', '📐'], question: '¿Cuál de estos NO estaba?', options: ['📚', '✏️', '📐', '📏'], answer: '📏' },
    { showItems: ['🎯', '🎲', '🃏'], question: '¿Cuál de estos estaba?', options: ['⚽', '🎲', '🎾', '🏆'], answer: '🎲' },
    { showItems: ['🍇', '🍓', '🍑'], question: '¿Cuál de estos NO estaba?', options: ['🍇', '🍓', '🍑', '🍒'], answer: '🍒' },
    { showItems: ['🚀', '🌍', '🛸'], question: '¿Cuál de estos estaba?', options: ['🌙', '⭐', '🌍', '🪐'], answer: '🌍' },
    { showItems: ['🎸', '🥁', '🎹'], question: '¿Cuál de estos NO estaba?', options: ['🎸', '🥁', '🎹', '🎺'], answer: '🎺' },
    { showItems: ['🐝', '🦋', '🐞'], question: '¿Cuál de estos estaba?', options: ['🐠', '🦋', '🐢', '🦎'], answer: '🦋' },
    { showItems: ['🍦', '🍰', '🍫'], question: '¿Cuál de estos NO estaba?', options: ['🍦', '🍰', '🍫', '🍬'], answer: '🍬' },
    { showItems: ['⛵', '🚢', '🛥️'], question: '¿Cuál de estos estaba?', options: ['✈️', '🚂', '⛵', '🚁'], answer: '⛵' },
    { showItems: ['🌵', '🌴', '🌳'], question: '¿Cuál de estos NO estaba?', options: ['🌵', '🌴', '🌳', '🌾'], answer: '🌾' },
    { showItems: ['🏆', '🥇', '🎖️'], question: '¿Cuál de estos estaba?', options: ['🎗️', '🏆', '🎁', '🎀'], answer: '🏆' },
    { showItems: ['🍞', '🥐', '🥨'], question: '¿Cuál de estos NO estaba?', options: ['🍞', '🥐', '🥨', '🥖'], answer: '🥖' },
    { showItems: ['🎃', '🎄', '🎆'], question: '¿Cuál de estos estaba?', options: ['🎈', '🎉', '🎃', '🎊'], answer: '🎃' },
    { showItems: ['🦊', '🐺', '🦝'], question: '¿Cuál de estos NO estaba?', options: ['🦊', '🐺', '🦝', '🐱'], answer: '🐱' },
    { showItems: ['🌞', '🌝', '🌛'], question: '¿Cuál de estos estaba?', options: ['⭐', '🌞', '☁️', '🌈'], answer: '🌞' },
    { showItems: ['🍵', '☕', '🧃'], question: '¿Cuál de estos NO estaba?', options: ['🍵', '☕', '🧃', '🥤'], answer: '🥤' },
    { showItems: ['🚂', '🚃', '🚄'], question: '¿Cuál de estos estaba?', options: ['🚗', '🚀', '🚂', '✈️'], answer: '🚂' },
    { showItems: ['🧲', '🔦', '🔑'], question: '¿Cuál de estos NO estaba?', options: ['🧲', '🔦', '🔑', '🔒'], answer: '🔒' },
    { showItems: ['🐙', '🦑', '🦀'], question: '¿Cuál de estos estaba?', options: ['🐟', '🐠', '🐙', '🐡'], answer: '🐙' },
    { showItems: ['🌂', '☂️', '🧣'], question: '¿Cuál de estos NO estaba?', options: ['🌂', '☂️', '🧣', '🧤'], answer: '🧤' },
    { showItems: ['🏔️', '🌋', '⛰️'], question: '¿Cuál de estos estaba?', options: ['🏖️', '🏝️', '🏔️', '🌊'], answer: '🏔️' },
    { showItems: ['🎭', '🎬', '🎪'], question: '¿Cuál de estos NO estaba?', options: ['🎭', '🎬', '🎪', '🎨'], answer: '🎨' },
    { showItems: ['🦜', '🦚', '🦩'], question: '¿Cuál de estos estaba?', options: ['🐓', '🦆', '🦜', '🦢'], answer: '🦜' },
  ],

  // ===== MEMORY PAIRS (50 emojis para mucha variedad) =====
  memoryEmojis: [
    '🎈','🎀','🌟','🍀','🎵','🌈','🦋','🌸','🍎','🎯',
    '🏆','🦁','🐬','🌺','🍕','🎭','🚀','🌙','⚡','🎪',
    '🌊','🐝','🍓','🎸','🦊','🌻','🐙','🍦','🎲','🦄',
    '🌴','🐠','🎨','🦒','🍰','🚂','🎃','🐳','🍇','🎺',
    '🌵','🍩','🎱','🦜','🌋','🐘','🎡','🦋','🍭','🏖️',
  ],

};
